### PR TITLE
Have MegaLinter apply fixes and only scan updated files

### PR DESCRIPTION
**Pull request by wesley-dean-gsa**
## Changes proposed in this pull request:

This will have MegaLinter only scan updated files (not the entire codebase) and will (eventually) include the `APPLY_FIXES` directive.

This PR also tells `CSS_STYLELINT` to not touch our `.scss` files.  When it runs -- particularly on the TTS styles file -- it makes breaking changes that result in builds failing.  So, we're disabling it for those files at this time.  The main thing it was tripping over was `//` comments (which, according to the [documentaton](https://sass-lang.com/documentation/syntax/comments/) are supported and are not to be carried over into the transpiled results).

## security considerations

The `REPOSITORY_` descriptor (group) contains the security checks.  Because all of these are always run against the entire repository, configuring MegaLinter to only scan changed files does not affect this group.  That is, the security checks will always run.

### CODE REVIEW

**Comment by wesley-dean-gsa** [comment]
The tests all pass and the site builds correctly before enabling `APPLY_FIXES`.

Screenshot_2023-09-29_08-50-44

**Comment by wesley-dean-gsa** [comment]
The tests all pass and the site builds before adding `APPLY_FIXES`

Screenshot_20240805_165118

**Comment by wesley-dean-gsa** [comment]
Please do not merge this until after #134 is merged.

**Comment by wesley-dean-gsa** [comment]
closes #139

**Review by narumigsa — APPROVED** [review]
approved

**Comment by wesley-dean-gsa** [comment]
A couple of notes on the remaining findings:

* scss-lint: I didn't change the selectors it's complaining about as they would require changing ids and classes throughout the CSS and HTML and I judge it's not work the effort at this moment.
* grype: at least 3 of the 6 findings will be resolved by running `npm audit fix` (which is done in a separate PR I'm working on)
* trivy: another Node dependency issue
* cspell: the "misspelling" is someone's name

**Pull request merged**
