### PR TITLE
Initial commit of a Bash script to extract YAML front matter

### PR DESCRIPTION
**Pull request by wesley-dean-gsa**
All this does is import a script to extract YAML front matter from a Markdown file.  It doesn't do any linting.

## security considerations

None come to mind.

### CODE REVIEW

**Comment by ximekilgsa** [comment]
@wesley-dean-gsa Can we chat about this? Just looking to understand what this does, if it's not linting, since we already have the YAML being rendered correctly

**Comment by wesley-dean-gsa** [comment]
This adds a script to actually do YAML linting on the Markdown front matter.  It's not set to run against anything, but at least it's a tool that exists.  We'll get it integrated in the next step.

**Comment by wesley-dean-gsa** [comment]
I'm not sure if this is the direction to take any more.  If we replace the Markdown files in pages/jointts/positions/ with YAML, then this becomes a non-issue.

**Comment by wesley-dean-gsa** [comment]
I'm putting this thing up for review as I judge it has some value that shouldn't necessarily be discarded, even if our processes include alternative mechanisms for helping content managers do their thing.

**Review by debjudy — APPROVED** [review]

**Pull request merged**
