### PR TITLE
Add commit signing

### PR DESCRIPTION
**Pull request by wesley-dean-gsa**
This will add commit signing with a GPG key.  Documentation on the commit action may be found here:

https://github.com/stefanzweifel/git-auto-commit-action#signing-commits

..and importing the GPG key may be found here:

https://github.com/crazy-max/ghaction-import-gpg

## security considerations

This will help us maintain the "force signed commits" option.

### CODE REVIEW

**Comment by wesley-dean-gsa** [comment]
We have opted not to enable script integrity hashes at this time.  Accepting this poses minimal risk given that of the three libraries being imported, two are TTS-supported (DAP and Search).  The decision will be further documented in an ADR.

**Comment by wesley-dean-gsa** [comment]
I closed the wrong PR.  Oopsies.

**Review by debjudy — APPROVED** [review]
approved 👍

**Comment by wesley-dean-gsa** [comment]
The repo is configured to require that commits must be signed.  Without signing, branches can't be merged:

Screenshot_20240826_150659

Those unsigned commits are coming from MegaLinter:

Screenshot_20240826_150744

**Pull request merged**
